function results = analyseRandTest(fileName)
%  Reads the results of a <randTest> experiment and plots the histogram of
%  results.
%     results = analyseRandTest(fileName)
%
%  "fileName" contains the path and name of the file to be read
%  "results" is an array with values generated by the <randGen>

fid= fopen(fileName,'rt');

if (fid<0) 
    fprintf(2,'Error opening file %s. Does it exist? Are you sure?\n',fileName);
    results = 0;
else
    results = fscanf(fid,'%g');
    hist(results,20);
    fclose(fid);
end



