analyseRandTest <- function(fileName)
#  Reads the results of a <randTest> experiment and plots the histogram of
#  results.
#     results = analyseRandTest(fileName)
#
#  "fileName" contains the path and name of the file to be read
#  "results" is an array with values generated by the <randGen>

{
	results <- scan(fileName)
	hist(results)
	results
}
