/*********************************************************************************************
 * Name		:  CompositeTaskCtTest1.h
 *
 * Purpose	:
 *
 * Notes	:  This file was generated by CORINET on Wed Dec 20 17:25:16 2006 
 *
 * Info		:  http://www.corinet.org
 *
 * Copyright:
 *
 * Licensce	: This program is free software; you can redistribute it and/or modify
 * 			   it under the terms of the GNU General Public License as published by
 * 			   the Free Software Foundation; either version 2 of the License, or
 * 			   (at your option) any later version.
 *
 * 			   This program is distributed in the hope that it will be useful,
 * 			   but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 			   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 			   GNU General Public License in $CORINETROOT/licenses for more details.
 *
 **********************************************************************************************/

#ifndef CORINET_TASKCTTEST1
#define CORINET_TASKCTTEST1

#include <Task/Impl/TaskImpl.h>

namespace CORINET {

class CTaskCtTest1 : public CTaskComposite {
	double mTestParam;
public:
	CTaskCtTest1(size_t*,double*);
	virtual ~CTaskCtTest1();
	void Initialise();
	void Finalise();
	void Generate(bool);
	void Seed(size_t);
	void SetParam(size_t,double);
	double GetParam(size_t);
};

} //end namespace CORINET

#endif //CORINET_TASKCTTEST1

