/*********************************************************************************************
 * Name		:  InsertInsertTest1.cpp
 *
 * Purpose	:
 *
 * Notes	:  This file was generated by CORINET on Wed Dec 20 17:25:16 2006 
 *
 * Info		:  http://www.corinet.org
 *
 * Copyright:
 *
 * Licensce	: This program is free software; you can redistribute it and/or modify
 * 			   it under the terms of the GNU General Public License as published by
 * 			   the Free Software Foundation; either version 2 of the License, or
 * 			   (at your option) any later version.
 *
 * 			   This program is distributed in the hope that it will be useful,
 * 			   but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 			   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 			   GNU General Public License in $CORINETROOT/licenses for more details.
 *
 **********************************************************************************************/


#include <Util/Factory.h>
#include <Util/Iterator.h>
#include "InsertInsertTest1.h"

namespace CORINET {

FInsertInsertTest1::FInsertInsertTest1(size_t* s,double* params)
{
	/*parameters available in s:
		s[0]: column in main pattern to insert subpatterns
		s[1]: row in main pattern to insert subpatterns*/

}

FInsertInsertTest1::~FInsertInsertTest1()
{

}

void FInsertInsertTest1::Initialise()
{
	/*you may delete this function here and in .h file if no action needs to be taken*/
}

void FInsertInsertTest1::operator()(bool randseq,MatrixIterator* pmat)
{
	/*insertText your code here*/
}

void FInsertInsertTest1::Finalise()
{
	/*you may delete this function here and in .h file if no action needs to be taken*/
}

void FInsertInsertTest1::SetParam(size_t p,double v)
{
	/*you may delete this function here and in .h if there are no parameters*/
}

double FInsertInsertTest1::GetParam(size_t p)
{
	/*you may delete this function here and in .h if there are no parameters*/
	return 0.0;
}

/*macro registers class name, see Factory.h for details*/
REGISTER_CLASS_1(FInsert,FInsertInsertTest1,insertTest1)

} //end namespace CORINET

